# Generated by Django 3.0.3 on 2020-03-10 18:51

import api.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=32)),
                ('_id', models.CharField(max_length=30)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[50, 50], upload_to=api.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='MergedImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=1500)),
                ('size', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/merged')),
            ],
        ),
    ]
